% REGRESSION_U03_APA03  Edge-case regression coverage for APA-03
% (Processor Cooling-Stack Analyzer) beyond the plain solved/unsolved
% fixtures that run.m/check_golden.m already cover.
%
% Each case materializes a deliberately broken or edge-case set of files
% into assignments/u03-apa03-processor-cooling/, runs the real rubric
% checker, and asserts a *specific* criterion fails or passes with an
% actionable message -- catching a regression in the checker itself, not
% grading student code. assignments/ is restored to the plain unsolved
% starter set when this finishes, matching run.m's contract.
%
% Not wired into check_golden.m (that script is solved/unsolved-only by
% design); run this by hand after changing
% tests/u03_apa03_processor_cooling_check.m:
%
%     octave-cli --no-gui --eval "setup; run('_verify/regression_u03_apa03.m')"

here = fileparts(mfilename('fullpath'));       % .../_verify
root = fileparts(here);                        % repo root
addpath(here);

unit = 'u03-apa03-processor-cooling';
assignDir = fullfile(root, 'assignments', unit);
solvedDir = fullfile(here, 'solved', unit);
unsolvedDir = fullfile(here, 'unsolved', unit);

fnNames = {'tim_resistance', 'processor_temperatures', 'thermal_margin'};

fprintf('\n########## regression: %s ##########\n', unit);

% ---------------------------------------------------------------------
% Case 1: a single personalized main filename is preferred over the
% (still-unsolved) generic starter.
% ---------------------------------------------------------------------
restoreUnitFiles(assignDir, solvedDir, fnNames);
copyfile(fullfile(unsolvedDir, 'U03_APA03_ProcessorCooling_Starter.m'), ...
         fullfile(assignDir, 'U03_APA03_ProcessorCooling_Starter.m'));
copyfile(fullfile(solvedDir, 'U03_APA03_ProcessorCooling_Starter.m'), ...
         fullfile(assignDir, 'APA03_ProcessorCooling_Smith.m'));
expectCriterion(unit, 'output', true, '', ...
  'Case 1: personalized main script preferred over unsolved generic starter');

% ---------------------------------------------------------------------
% Case 2: two ambiguous personalized main filenames stop with an
% actionable message instead of silently choosing one.
% ---------------------------------------------------------------------
restoreUnitFiles(assignDir, solvedDir, fnNames);
copyfile(fullfile(assignDir, 'U03_APA03_ProcessorCooling_Starter.m'), ...
         fullfile(assignDir, 'APA03_ProcessorCooling_Smith.m'));
copyfile(fullfile(assignDir, 'U03_APA03_ProcessorCooling_Starter.m'), ...
         fullfile(assignDir, 'APA03_ProcessorCooling_Jones.m'));
expectCriterion(unit, 'resolves', false, 'more than one', ...
  'Case 2: ambiguous personalized main filenames');
delete(fullfile(assignDir, 'APA03_ProcessorCooling_Smith.m'));
delete(fullfile(assignDir, 'APA03_ProcessorCooling_Jones.m'));

% ---------------------------------------------------------------------
% Case 3: tim_resistance is missing the square-millimeter-to-square-meter
% conversion (area left in mm^2).
% ---------------------------------------------------------------------
restoreUnitFiles(assignDir, solvedDir, fnNames);
writeLines(fullfile(assignDir, 'tim_resistance.m'), { ...
  'function resistance_C_per_W = tim_resistance( ...', ...
  '    thickness_mm, conductivity_W_mK, area_mm2)', ...
  '%TIM_RESISTANCE Buggy: missing area unit conversion.', ...
  '%   thickness_mm is a scalar or vector thickness in millimeters.', ...
  '%   conductivity_W_mK is conductivity in W/(m*K). area_mm2 is area in', ...
  '%   square millimeters. resistance_C_per_W is resistance in C/W and', ...
  '%   supports scalar or vector input under a one-dimensional, constant-', ...
  '%   property assumption.', ...
  '', ...
  'thickness_m = thickness_mm ./ 1000;', ...
  '', ...
  'resistance_C_per_W = thickness_m ./ (conductivity_W_mK .* area_mm2);', ...
  '', ...
  'end' ...
});
clear(fnNames{:});
expectCriterion(unit, 'tim_resistance: unit conversions', false, '', ...
  'Case 3: tim_resistance missing area unit conversion');

% ---------------------------------------------------------------------
% Case 4: tim_resistance silently collapses a vector input to its first
% element (a "scalar-only" implementation).
% ---------------------------------------------------------------------
restoreUnitFiles(assignDir, solvedDir, fnNames);
writeLines(fullfile(assignDir, 'tim_resistance.m'), { ...
  'function resistance_C_per_W = tim_resistance( ...', ...
  '    thickness_mm, conductivity_W_mK, area_mm2)', ...
  '%TIM_RESISTANCE Buggy: scalar-only, ignores vector shape.', ...
  '%   thickness_mm is a scalar or vector thickness in millimeters.', ...
  '%   conductivity_W_mK is conductivity in W/(m*K). area_mm2 is area in', ...
  '%   square millimeters. resistance_C_per_W is resistance in C/W and', ...
  '%   supports scalar or vector input under a one-dimensional, constant-', ...
  '%   property assumption.', ...
  '', ...
  'thickness_m = thickness_mm(1) ./ 1000;', ...
  'area_m2 = area_mm2 ./ 1e6;', ...
  '', ...
  'resistance_C_per_W = thickness_m ./ (conductivity_W_mK .* area_m2);', ...
  '', ...
  'end' ...
});
clear(fnNames{:});
expectCriterion(unit, 'tim_resistance: unit conversions', false, '', ...
  'Case 4: tim_resistance collapses vector input to scalar');

% ---------------------------------------------------------------------
% Case 5: processor_temperatures returns its three outputs in the wrong
% order (junction first).
% ---------------------------------------------------------------------
restoreUnitFiles(assignDir, solvedDir, fnNames);
writeLines(fullfile(assignDir, 'processor_temperatures.m'), { ...
  'function [heatsink_base_C, ihs_surface_C, junction_C] = ...', ...
  '    processor_temperatures(power_W, ambient_C, ...', ...
  '    package_ihs_resistance_C_per_W, tim_resistance_C_per_W, ...', ...
  '    heatsink_resistance_C_per_W)', ...
  '%PROCESSOR_TEMPERATURES Buggy: outputs swapped (junction first).', ...
  '%   power_W is scalar or vector power in watts. ambient_C is ambient', ...
  '%   temperature in degrees Celsius. The three resistance inputs are in', ...
  '%   C/W. Outputs are heat-sink base, IHS surface, and junction', ...
  '%   temperature in degrees Celsius under a steady-state assumption.', ...
  '', ...
  'base_temp = ambient_C + power_W .* heatsink_resistance_C_per_W;', ...
  'ihs_temp = base_temp + power_W .* tim_resistance_C_per_W;', ...
  'junction_temp = ihs_temp + power_W .* package_ihs_resistance_C_per_W;', ...
  '', ...
  'heatsink_base_C = junction_temp;', ...
  'ihs_surface_C = ihs_temp;', ...
  'junction_C = base_temp;', ...
  '', ...
  'end' ...
});
clear(fnNames{:});
expectCriterion(unit, 'processor_temperatures: node order', false, '', ...
  'Case 5: processor_temperatures swaps output node order');

% ---------------------------------------------------------------------
% Case 6: thermal_margin has its sign reversed.
% ---------------------------------------------------------------------
restoreUnitFiles(assignDir, solvedDir, fnNames);
writeLines(fullfile(assignDir, 'thermal_margin.m'), { ...
  'function margin_C = thermal_margin(maximum_junction_C, junction_C)', ...
  '%THERMAL_MARGIN Buggy: sign reversed.', ...
  '%   maximum_junction_C is the allowed maximum in degrees Celsius.', ...
  '%   junction_C is a scalar or vector actual temperature in degrees', ...
  '%   Celsius. margin_C preserves input shape. Positive margin is below', ...
  '%   the limit, zero is exactly at the limit, and negative is above it.', ...
  '', ...
  'margin_C = junction_C - maximum_junction_C;', ...
  '', ...
  'end' ...
});
clear(fnNames{:});
expectCriterion(unit, 'thermal_margin: sign', false, '', ...
  'Case 6: thermal_margin sign reversed');

% ---------------------------------------------------------------------
% Case 7: main script's within_limit excludes zero margin (uses > 0).
% ---------------------------------------------------------------------
restoreUnitFiles(assignDir, solvedDir, fnNames);
mainLines = strsplit(fileread(fullfile(solvedDir, 'U03_APA03_ProcessorCooling_Starter.m')), sprintf('\n'));
for k = 1:numel(mainLines)
  if ~isempty(strfind(mainLines{k}, 'within_limit = margin_C >= 0;'))
    mainLines{k} = 'within_limit = margin_C > 0;';
  end
end
writeLines(fullfile(assignDir, 'U03_APA03_ProcessorCooling_Starter.m'), mainLines);
clear(fnNames{:});
expectCriterion(unit, 'calls all three functions', false, 'zero margin', ...
  'Case 7: within_limit excludes zero margin');

% ---------------------------------------------------------------------
% Case 8: results matrix columns are transposed/swapped.
% ---------------------------------------------------------------------
restoreUnitFiles(assignDir, solvedDir, fnNames);
mainLines = strsplit(fileread(fullfile(solvedDir, 'U03_APA03_ProcessorCooling_Starter.m')), sprintf('\n'));
for k = 1:numel(mainLines)
  if ~isempty(strfind(mainLines{k}, 'junction_C(:), margin_C(:), within_limit(:)];'))
    mainLines{k} = 'within_limit(:), margin_C(:), junction_C(:)];';
  end
end
writeLines(fullfile(assignDir, 'U03_APA03_ProcessorCooling_Starter.m'), mainLines);
clear(fnNames{:});
expectCriterion(unit, 'calls all three functions', false, '', ...
  'Case 8: results matrix columns swapped');

% ---------------------------------------------------------------------
% restore assignments/ to the plain unsolved starter set
% ---------------------------------------------------------------------
restoreUnitFiles(assignDir, unsolvedDir, fnNames);
fprintf('Done. assignments/%s restored to unsolved stubs.\n', unit);
