% REGRESSION_U04_APA04  Edge-case regression coverage for APA-04
% (Validated Model-Rocket Parachute Sizing Tool) beyond the plain
% solved/unsolved fixtures that run.m/check_golden.m already cover.
%
% Each case materializes a deliberately broken set of files into
% assignments/u04-apa04-parachute-sizing/, runs the real rubric checker,
% and asserts a *specific* criterion fails with an actionable message --
% catching a regression in the checker itself, not grading student code.
% assignments/ is restored to the plain unsolved starter set when this
% finishes, matching run.m's contract.
%
% Not wired into check_golden.m (that script is solved/unsolved-only by
% design); run this by hand after changing
% tests/u04_apa04_parachute_sizing_check.m:
%
%     octave-cli --no-gui --eval "setup; run('_verify/regression_u04_apa04.m')"

here = fileparts(mfilename('fullpath'));       % .../_verify
root = fileparts(here);                        % repo root
addpath(here);

unit = 'u04-apa04-parachute-sizing';
assignDir = fullfile(root, 'assignments', unit);
solvedDir = fullfile(here, 'solved', unit);
unsolvedDir = fullfile(here, 'unsolved', unit);

fnNames = {'parachute_speed', 'size_parachute'};

fprintf('\n########## regression: %s ##########\n', unit);

% ---------------------------------------------------------------------
% Case 1: hard-coded published 0.80 m answer.
% ---------------------------------------------------------------------
restoreUnitFiles(assignDir, solvedDir, fnNames);
writeLines(fullfile(assignDir, 'size_parachute.m'), { ...
  'function [diameter_m, speed_mps, feasible, iterations] = ...', ...
  '    size_parachute(mass_kg, target_speed_mps, max_diameter_m, diameter_step_m)', ...
  '  % SIZE_PARACHUTE Buggy: hard-codes the published 0.80 m answer.', ...
  '  min_diameter_m = 0.30;', ...
  '  if ~isnumeric(mass_kg) || ~isscalar(mass_kg) || ~isfinite(mass_kg) || mass_kg <= 0', ...
  '    error(''bad mass_kg'');', ...
  '  end', ...
  '  if ~isnumeric(target_speed_mps) || ~isscalar(target_speed_mps) || ...', ...
  '      ~isfinite(target_speed_mps) || target_speed_mps <= 0', ...
  '    error(''bad target_speed_mps'');', ...
  '  end', ...
  '  if ~isnumeric(max_diameter_m) || ~isscalar(max_diameter_m) || ...', ...
  '      ~isfinite(max_diameter_m) || max_diameter_m <= 0', ...
  '    error(''bad max_diameter_m'');', ...
  '  end', ...
  '  if ~isnumeric(diameter_step_m) || ~isscalar(diameter_step_m) || ...', ...
  '      ~isfinite(diameter_step_m) || diameter_step_m <= 0', ...
  '    error(''bad diameter_step_m'');', ...
  '  end', ...
  '  if max_diameter_m < min_diameter_m', ...
  '    error(''max too small'');', ...
  '  end', ...
  '  diameter_m = 0.80;', ...
  '  speed_mps = parachute_speed(mass_kg, diameter_m);', ...
  '  feasible = speed_mps <= target_speed_mps;', ...
  '  iterations = 6;', ...
  'end' ...
});
clear(fnNames{:});
expectCriterion(unit, 'general (nonpublished) cases', false, '', ...
  'Case 1: size_parachute hard-codes the published 0.80 m answer');

% ---------------------------------------------------------------------
% Case 2: boundary mistake -- strict < instead of <= for feasibility.
% ---------------------------------------------------------------------
restoreUnitFiles(assignDir, solvedDir, fnNames);
writeLines(fullfile(assignDir, 'size_parachute.m'), { ...
  'function [diameter_m, speed_mps, feasible, iterations] = ...', ...
  '    size_parachute(mass_kg, target_speed_mps, max_diameter_m, diameter_step_m)', ...
  '  % SIZE_PARACHUTE Buggy: strict < instead of <= for feasibility.', ...
  '  min_diameter_m = 0.30;', ...
  '  if ~isnumeric(mass_kg) || ~isscalar(mass_kg) || ~isfinite(mass_kg) || mass_kg <= 0', ...
  '    error(''bad mass_kg'');', ...
  '  end', ...
  '  if ~isnumeric(target_speed_mps) || ~isscalar(target_speed_mps) || ...', ...
  '      ~isfinite(target_speed_mps) || target_speed_mps <= 0', ...
  '    error(''bad target_speed_mps'');', ...
  '  end', ...
  '  if ~isnumeric(max_diameter_m) || ~isscalar(max_diameter_m) || ...', ...
  '      ~isfinite(max_diameter_m) || max_diameter_m <= 0', ...
  '    error(''bad max_diameter_m'');', ...
  '  end', ...
  '  if ~isnumeric(diameter_step_m) || ~isscalar(diameter_step_m) || ...', ...
  '      ~isfinite(diameter_step_m) || diameter_step_m <= 0', ...
  '    error(''bad diameter_step_m'');', ...
  '  end', ...
  '  if max_diameter_m < min_diameter_m', ...
  '    error(''max too small'');', ...
  '  end', ...
  '  diameter_m = min_diameter_m;', ...
  '  speed_mps = Inf;', ...
  '  feasible = false;', ...
  '  iterations = 0;', ...
  '  max_iterations = ceil((max_diameter_m - min_diameter_m) / diameter_step_m) + 1;', ...
  '  while iterations < max_iterations', ...
  '    candidate_m = min_diameter_m + iterations * diameter_step_m;', ...
  '    if candidate_m >= max_diameter_m', ...
  '      candidate_m = max_diameter_m;', ...
  '    end', ...
  '    iterations = iterations + 1;', ...
  '    diameter_m = candidate_m;', ...
  '    speed_mps = parachute_speed(mass_kg, diameter_m);', ...
  '    feasible = speed_mps < target_speed_mps;', ...
  '    if feasible || candidate_m >= max_diameter_m', ...
  '      break;', ...
  '    end', ...
  '  end', ...
  'end' ...
});
clear(fnNames{:});
expectCriterion(unit, 'published and boundary search', false, '', ...
  'Case 2: size_parachute uses strict < instead of <= for feasibility');

% ---------------------------------------------------------------------
% Case 3: row/column shape mistake -- parachute_speed always returns a
% row vector regardless of diameter_m's shape.
% ---------------------------------------------------------------------
restoreUnitFiles(assignDir, solvedDir, fnNames);
writeLines(fullfile(assignDir, 'parachute_speed.m'), { ...
  'function speed_mps = parachute_speed(mass_kg, diameter_m)', ...
  '  % PARACHUTE_SPEED Buggy: always returns a row vector.', ...
  '  g_mps2 = 9.81;', ...
  '  air_density_kgpm3 = 1.225;', ...
  '  drag_coefficient = 0.75;', ...
  '  if ~isnumeric(mass_kg) || ~isscalar(mass_kg) || ~isfinite(mass_kg) || mass_kg <= 0', ...
  '    error(''bad mass_kg'');', ...
  '  end', ...
  '  if ~isnumeric(diameter_m) || isempty(diameter_m) || ...', ...
  '      ~all(isfinite(diameter_m(:))) || ~all(diameter_m(:) > 0)', ...
  '    error(''bad diameter_m'');', ...
  '  end', ...
  '  diameter_m = diameter_m(:).'';', ...
  '  area_m2 = pi .* diameter_m.^2 ./ 4;', ...
  '  speed_mps = sqrt((2 .* mass_kg .* g_mps2) ./ ...', ...
  '                    (air_density_kgpm3 .* drag_coefficient .* area_m2));', ...
  'end' ...
});
clear(fnNames{:});
expectCriterion(unit, 'model calculations are correct', false, '', ...
  'Case 3: parachute_speed always returns a row vector');

% ---------------------------------------------------------------------
% Case 4: missing maximum-candidate handling -- the loop stops as soon as
% the next step would exceed max_diameter_m, without testing the maximum
% itself as the final candidate.
% ---------------------------------------------------------------------
restoreUnitFiles(assignDir, solvedDir, fnNames);
writeLines(fullfile(assignDir, 'size_parachute.m'), { ...
  'function [diameter_m, speed_mps, feasible, iterations] = ...', ...
  '    size_parachute(mass_kg, target_speed_mps, max_diameter_m, diameter_step_m)', ...
  '  % SIZE_PARACHUTE Buggy: never tests max_diameter_m as a final,', ...
  '  % non-aligned candidate -- it only ever tests exact step multiples.', ...
  '  min_diameter_m = 0.30;', ...
  '  if ~isnumeric(mass_kg) || ~isscalar(mass_kg) || ~isfinite(mass_kg) || mass_kg <= 0', ...
  '    error(''bad mass_kg'');', ...
  '  end', ...
  '  if ~isnumeric(target_speed_mps) || ~isscalar(target_speed_mps) || ...', ...
  '      ~isfinite(target_speed_mps) || target_speed_mps <= 0', ...
  '    error(''bad target_speed_mps'');', ...
  '  end', ...
  '  if ~isnumeric(max_diameter_m) || ~isscalar(max_diameter_m) || ...', ...
  '      ~isfinite(max_diameter_m) || max_diameter_m <= 0', ...
  '    error(''bad max_diameter_m'');', ...
  '  end', ...
  '  if ~isnumeric(diameter_step_m) || ~isscalar(diameter_step_m) || ...', ...
  '      ~isfinite(diameter_step_m) || diameter_step_m <= 0', ...
  '    error(''bad diameter_step_m'');', ...
  '  end', ...
  '  if max_diameter_m < min_diameter_m', ...
  '    error(''max too small'');', ...
  '  end', ...
  '  diameter_m = min_diameter_m;', ...
  '  speed_mps = Inf;', ...
  '  feasible = false;', ...
  '  iterations = 0;', ...
  '  max_iterations = ceil((max_diameter_m - min_diameter_m) / diameter_step_m) + 1;', ...
  '  candidate_m = min_diameter_m;', ...
  '  while iterations < max_iterations && candidate_m <= max_diameter_m', ...
  '    iterations = iterations + 1;', ...
  '    diameter_m = candidate_m;', ...
  '    speed_mps = parachute_speed(mass_kg, diameter_m);', ...
  '    feasible = speed_mps <= target_speed_mps;', ...
  '    if feasible', ...
  '      break;', ...
  '    end', ...
  '    candidate_m = candidate_m + diameter_step_m;', ...
  '  end', ...
  'end' ...
});
clear(fnNames{:});
expectCriterion(unit, 'published and boundary search', false, '', ...
  'Case 4: size_parachute never tests max_diameter_m as a final non-aligned candidate');

% ---------------------------------------------------------------------
% Case 5: missing validation -- size_parachute never checks any input.
% ---------------------------------------------------------------------
restoreUnitFiles(assignDir, solvedDir, fnNames);
writeLines(fullfile(assignDir, 'size_parachute.m'), { ...
  'function [diameter_m, speed_mps, feasible, iterations] = ...', ...
  '    size_parachute(mass_kg, target_speed_mps, max_diameter_m, diameter_step_m)', ...
  '  % SIZE_PARACHUTE Buggy: no input validation at all.', ...
  '  min_diameter_m = 0.30;', ...
  '  diameter_m = min_diameter_m;', ...
  '  speed_mps = Inf;', ...
  '  feasible = false;', ...
  '  iterations = 0;', ...
  '  max_iterations = ceil((max_diameter_m - min_diameter_m) / diameter_step_m) + 1;', ...
  '  while iterations < max_iterations', ...
  '    candidate_m = min_diameter_m + iterations * diameter_step_m;', ...
  '    if candidate_m >= max_diameter_m', ...
  '      candidate_m = max_diameter_m;', ...
  '    end', ...
  '    iterations = iterations + 1;', ...
  '    diameter_m = candidate_m;', ...
  '    speed_mps = parachute_speed(mass_kg, diameter_m);', ...
  '    feasible = speed_mps <= target_speed_mps;', ...
  '    if feasible || candidate_m >= max_diameter_m', ...
  '      break;', ...
  '    end', ...
  '  end', ...
  'end' ...
});
clear(fnNames{:});
expectCriterion(unit, 'size_parachute: invalid inputs raise an error', false, '', ...
  'Case 5: size_parachute has no input validation at all');

% ---------------------------------------------------------------------
% restore assignments/ to the plain unsolved starter set
% ---------------------------------------------------------------------
restoreUnitFiles(assignDir, unsolvedDir, fnNames);
fprintf('Done. assignments/%s restored to unsolved stubs.\n', unit);
