% REGRESSION_U04_GP04  Edge-case regression coverage for GP-04 (Processor
% Thermal Safety Monitor) beyond the plain solved/unsolved fixtures that
% run.m/check_golden.m already cover.
%
% Each case materializes a deliberately broken set of files into
% assignments/u04-gp04-thermal-monitor/, runs the real rubric checker,
% and asserts a *specific* criterion fails with an actionable message --
% catching a regression in the checker itself, not grading student code.
% assignments/ is restored to the plain unsolved starter set when this
% finishes, matching run.m's contract.
%
% Not wired into check_golden.m (that script is solved/unsolved-only by
% design); run this by hand after changing
% tests/u04_gp04_thermal_monitor_check.m:
%
%     octave-cli --no-gui --eval "setup; run('_verify/regression_u04_gp04.m')"

here = fileparts(mfilename('fullpath'));       % .../_verify
root = fileparts(here);                        % repo root
addpath(here);

unit = 'u04-gp04-thermal-monitor';
assignDir = fullfile(root, 'assignments', unit);
solvedDir = fullfile(here, 'solved', unit);
unsolvedDir = fullfile(here, 'unsolved', unit);

fnNames = {'classify_temperature', 'analyze_thermal_log'};

fprintf('\n########## regression: %s ##########\n', unit);

% ---------------------------------------------------------------------
% Case 1: boundary mistake -- strict > instead of >= at both thresholds.
% ---------------------------------------------------------------------
restoreUnitFiles(assignDir, solvedDir, fnNames);
writeLines(fullfile(assignDir, 'classify_temperature.m'), { ...
  'function status_code = classify_temperature(temp_C, warning_C, shutdown_C)', ...
  '  % CLASSIFY_TEMPERATURE Buggy: strict > instead of >= at both thresholds.', ...
  '  if ~isnumeric(temp_C) || ~isscalar(temp_C) || ~isfinite(temp_C)', ...
  '    error(''bad temp_C'');', ...
  '  end', ...
  '  if ~isnumeric(warning_C) || ~isscalar(warning_C) || ~isfinite(warning_C)', ...
  '    error(''bad warning_C'');', ...
  '  end', ...
  '  if ~isnumeric(shutdown_C) || ~isscalar(shutdown_C) || ~isfinite(shutdown_C)', ...
  '    error(''bad shutdown_C'');', ...
  '  end', ...
  '  if ~(warning_C < shutdown_C)', ...
  '    error(''bad thresholds'');', ...
  '  end', ...
  '  if temp_C > shutdown_C', ...
  '    status_code = 2;', ...
  '  elseif temp_C > warning_C', ...
  '    status_code = 1;', ...
  '  else', ...
  '    status_code = 0;', ...
  '  end', ...
  'end' ...
});
clear(fnNames{:});
expectCriterion(unit, 'boundary classification', false, '', ...
  'Case 1: classify_temperature uses strict > instead of >=');

% ---------------------------------------------------------------------
% Case 2: missing threshold-order validation (warning_C < shutdown_C
% never checked).
% ---------------------------------------------------------------------
restoreUnitFiles(assignDir, solvedDir, fnNames);
writeLines(fullfile(assignDir, 'classify_temperature.m'), { ...
  'function status_code = classify_temperature(temp_C, warning_C, shutdown_C)', ...
  '  % CLASSIFY_TEMPERATURE Buggy: never validates warning_C < shutdown_C.', ...
  '  if ~isnumeric(temp_C) || ~isscalar(temp_C) || ~isfinite(temp_C)', ...
  '    error(''bad temp_C'');', ...
  '  end', ...
  '  if ~isnumeric(warning_C) || ~isscalar(warning_C) || ~isfinite(warning_C)', ...
  '    error(''bad warning_C'');', ...
  '  end', ...
  '  if ~isnumeric(shutdown_C) || ~isscalar(shutdown_C) || ~isfinite(shutdown_C)', ...
  '    error(''bad shutdown_C'');', ...
  '  end', ...
  '  if temp_C >= shutdown_C', ...
  '    status_code = 2;', ...
  '  elseif temp_C >= warning_C', ...
  '    status_code = 1;', ...
  '  else', ...
  '    status_code = 0;', ...
  '  end', ...
  'end' ...
});
clear(fnNames{:});
expectCriterion(unit, 'classify_temperature: invalid', false, '', ...
  'Case 2: classify_temperature never validates warning_C < shutdown_C');

% ---------------------------------------------------------------------
% Case 3: row/column shape mistake -- status_codes always a row vector.
% ---------------------------------------------------------------------
restoreUnitFiles(assignDir, solvedDir, fnNames);
writeLines(fullfile(assignDir, 'analyze_thermal_log.m'), { ...
  'function [status_codes, first_warning_index, first_shutdown_index] = ...', ...
  '    analyze_thermal_log(core_temps_C, warning_C, shutdown_C)', ...
  '  % ANALYZE_THERMAL_LOG Buggy: always returns a row vector.', ...
  '  if ~isnumeric(core_temps_C) || isempty(core_temps_C) || ~isvector(core_temps_C) || ...', ...
  '      ~all(isfinite(core_temps_C(:)))', ...
  '    error(''bad core_temps_C'');', ...
  '  end', ...
  '  if ~isnumeric(warning_C) || ~isscalar(warning_C) || ~isfinite(warning_C)', ...
  '    error(''bad warning_C'');', ...
  '  end', ...
  '  if ~isnumeric(shutdown_C) || ~isscalar(shutdown_C) || ~isfinite(shutdown_C)', ...
  '    error(''bad shutdown_C'');', ...
  '  end', ...
  '  if ~(warning_C < shutdown_C)', ...
  '    error(''bad thresholds'');', ...
  '  end', ...
  '  status_codes = zeros(1, numel(core_temps_C));', ...
  '  first_warning_index = 0;', ...
  '  first_shutdown_index = 0;', ...
  '  for k = 1:numel(core_temps_C)', ...
  '    status_codes(k) = classify_temperature(core_temps_C(k), warning_C, shutdown_C);', ...
  '    if status_codes(k) >= 1 && first_warning_index == 0', ...
  '      first_warning_index = k;', ...
  '    end', ...
  '    if status_codes(k) == 2 && first_shutdown_index == 0', ...
  '      first_shutdown_index = k;', ...
  '    end', ...
  '  end', ...
  'end' ...
});
clear(fnNames{:});
expectCriterion(unit, 'shape is preserved', false, '', ...
  'Case 3: analyze_thermal_log always returns a row vector');

% ---------------------------------------------------------------------
% Case 4: missing matrix rejection (isvector never checked).
% ---------------------------------------------------------------------
restoreUnitFiles(assignDir, solvedDir, fnNames);
writeLines(fullfile(assignDir, 'analyze_thermal_log.m'), { ...
  'function [status_codes, first_warning_index, first_shutdown_index] = ...', ...
  '    analyze_thermal_log(core_temps_C, warning_C, shutdown_C)', ...
  '  % ANALYZE_THERMAL_LOG Buggy: never rejects a matrix input.', ...
  '  if ~isnumeric(core_temps_C) || isempty(core_temps_C) || ...', ...
  '      ~all(isfinite(core_temps_C(:)))', ...
  '    error(''bad core_temps_C'');', ...
  '  end', ...
  '  if ~isnumeric(warning_C) || ~isscalar(warning_C) || ~isfinite(warning_C)', ...
  '    error(''bad warning_C'');', ...
  '  end', ...
  '  if ~isnumeric(shutdown_C) || ~isscalar(shutdown_C) || ~isfinite(shutdown_C)', ...
  '    error(''bad shutdown_C'');', ...
  '  end', ...
  '  if ~(warning_C < shutdown_C)', ...
  '    error(''bad thresholds'');', ...
  '  end', ...
  '  status_codes = zeros(size(core_temps_C));', ...
  '  first_warning_index = 0;', ...
  '  first_shutdown_index = 0;', ...
  '  for k = 1:numel(core_temps_C)', ...
  '    status_codes(k) = classify_temperature(core_temps_C(k), warning_C, shutdown_C);', ...
  '    if status_codes(k) >= 1 && first_warning_index == 0', ...
  '      first_warning_index = k;', ...
  '    end', ...
  '    if status_codes(k) == 2 && first_shutdown_index == 0', ...
  '      first_shutdown_index = k;', ...
  '    end', ...
  '  end', ...
  'end' ...
});
clear(fnNames{:});
expectCriterion(unit, 'analyze_thermal_log: invalid', false, '', ...
  'Case 4: analyze_thermal_log never rejects a matrix input');

% ---------------------------------------------------------------------
% restore assignments/ to the plain unsolved starter set
% ---------------------------------------------------------------------
restoreUnitFiles(assignDir, unsolvedDir, fnNames);
fprintf('Done. assignments/%s restored to unsolved stubs.\n', unit);
