function specs = u02_gp02_tensile_tests()
%U02_GP02_TENSILE_TESTS  Rubric criteria for Unit 2's GP-02 guided-practice
%   exercise: Tensile-Test Data Analysis.
%
%   This is a guided-practice exercise, not a graded Canvas submission --
%   students follow the instructor's video, run these checks as many times
%   as they like, and use the arrows as hints. All 7 criteria below map
%   one-to-one to the 7 checkpoints in the assignment (Inspect, Transform,
%   Retrieve, Locate UTS, Select, Organize, Report); each is worth 1 point
%   so the report reads as "N of 7 checkpoints" at a glance.
%
%   The actual checking logic lives in u02_gp02_tensile_check.m, which
%   resolves the student's script, runs it in an isolated workspace, and
%   reports back one of the criteria below.

  S = @engr183.spec;   % shorthand: name, fn, args, expected, points [, tol]
  U = 'u02_gp02_tensile_check';

  specs = { ...
    S('Checkpoint 1 (Inspect): data untouched; size/length/count correct', ...
      U, {'checkpoint1_inspect'}, true, 1), ...

    S('Checkpoint 2 (Transform): area, stress, and strain are correct', ...
      U, {'checkpoint2_transform'}, true, 1), ...

    S('Checkpoint 3 (Retrieve): fifth/last measurements retrieved correctly', ...
      U, {'checkpoint3_retrieve'}, true, 1), ...

    S('Checkpoint 4 (Locate UTS): ultimate strength and its index are correct', ...
      U, {'checkpoint4_locate_uts'}, true, 1), ...

    S('Checkpoint 5 (Select): early-region mask and stresses are correct', ...
      U, {'checkpoint5_select'}, true, 1), ...

    S('Checkpoint 6 (Organize): results matrix is the correct 39-by-4 shape', ...
      U, {'checkpoint6_organize'}, true, 1), ...

    S('Checkpoint 7 (Report): printed output matches the required lines', ...
      U, {'checkpoint7_report'}, true, 1), ...
  };
end
