function specs = u03_apa03_processor_cooling_tests()
%U03_APA03_PROCESSOR_COOLING_TESTS  Rubric criteria for Unit 3's APA-03:
%   Processor Cooling-Stack Analyzer.
%
%   16 of this Canvas assignment's 20 points are automated code checks,
%   below. The remaining 4 points are manually graded in Canvas: the
%   three written interpretation responses (TODO 7) and overall label/
%   unit/formatting quality -- an automated 16/16 here is not the same
%   thing as your full Canvas grade.
%
%   The actual checking logic lives in u03_apa03_processor_cooling_check.m,
%   which resolves the student's files, runs them in isolated workspaces,
%   and reports back one of the criteria below. Mirrors unit02_check.m /
%   u02_gp02_tensile_check.m's shape.

  S = @engr183.spec;   % shorthand: name, fn, args, expected, points [, tol]
  U = 'u03_apa03_processor_cooling_check';

  specs = { ...
    S('Required files: 3 function files and the main script exist', ...
      U, {'required_function_files'}, true, 1), ...

    S('Supplied public-check file exists and is runnable', ...
      U, {'public_check_present'}, true, 1), ...

    S('Main script resolves without ambiguity', ...
      U, {'main_script_resolves'}, true, 1), ...

    S('tim_resistance declares exactly 3 inputs and 1 output', ...
      U, {'tim_resistance_interface'}, true, 1), ...

    S('processor_temperatures declares exactly 5 inputs and 3 outputs', ...
      U, {'processor_temperatures_interface'}, true, 1), ...

    S('thermal_margin declares exactly 2 inputs and 1 output', ...
      U, {'thermal_margin_interface'}, true, 1), ...

    S('tim_resistance: unit conversions and vector shape are correct', ...
      U, {'tim_resistance_correctness'}, true, 1), ...

    S('processor_temperatures: node order, shapes, and scenario values are correct', ...
      U, {'processor_temperatures_correctness'}, true, 2), ...

    S('thermal_margin: sign, shape, and nondefault limit are correct', ...
      U, {'thermal_margin_correctness'}, true, 1), ...

    S('Function help documentation is complete for all three functions', ...
      U, {'function_help_documentation'}, true, 1), ...

    S('Public check passes on a completed implementation', ...
      U, {'public_check_passes_when_solved'}, true, 1), ...

    S('Main script: calls all three functions and assembles correct results', ...
      U, {'main_script_integration'}, true, 3), ...

    S('Main script: prints the four required output lines', ...
      U, {'main_script_output'}, true, 1), ...
  };
end
