function specs = u03_gp03_thermistor_tests()
%U03_GP03_THERMISTOR_TESTS  Rubric criteria for Unit 3's GP-03: Thermistor
%   Sensor Functions.
%
%   9 of this Canvas assignment's 10 points are automated code checks,
%   below. The remaining 1 point is manually graded in Canvas: the two
%   written reflection comments (TODO 9) -- an automated 9/9 here is not
%   the same thing as your full Canvas grade.
%
%   The actual checking logic lives in u03_gp03_thermistor_check.m, which
%   resolves the student's files, runs them in isolated workspaces, and
%   reports back one of the criteria below. Mirrors unit02_check.m /
%   u03_apa03_processor_cooling_check.m's shape.

  S = @engr183.spec;   % shorthand: name, fn, args, expected, points [, tol]
  U = 'u03_gp03_thermistor_check';

  specs = { ...
    S('Required files: both function files and the main script exist', ...
      U, {'required_function_files'}, true, 1), ...

    S('Main script resolves without ambiguity', ...
      U, {'main_script_resolves'}, true, 1), ...

    S('thermistor_resistance declares exactly 3 inputs and 1 output', ...
      U, {'thermistor_resistance_interface'}, true, 1), ...

    S('thermistor_temperature declares exactly 4 inputs and 1 output', ...
      U, {'thermistor_temperature_interface'}, true, 1), ...

    S('thermistor_resistance: divider equation and vector shape are correct', ...
      U, {'thermistor_resistance_correctness'}, true, 1), ...

    S('thermistor_temperature: beta model and vector shape are correct', ...
      U, {'thermistor_temperature_correctness'}, true, 1), ...

    S('Function help documentation is complete for both functions', ...
      U, {'function_help_documentation'}, true, 1), ...

    S('Main script: calls both functions and assembles correct results', ...
      U, {'main_script_integration'}, true, 1), ...

    S('Main script: prints the five required output lines', ...
      U, {'main_script_output'}, true, 1), ...
  };
end
