function specs = u04_apa04_parachute_sizing_tests()
%U04_APA04_PARACHUTE_SIZING_TESTS  Rubric criteria for Unit 4's APA-04:
%   Validated Model-Rocket Parachute Sizing Tool.
%
%   Run Tests calls parachute_speed and size_parachute directly (per the
%   assignment's own design). It includes every public-check behavior
%   plus broader cases that discourage hard-coding the published 0.80 m
%   answer. The actual checking logic lives in
%   u04_apa04_parachute_sizing_check.m, which mirrors unit02_check.m /
%   u03_apa03_processor_cooling_check.m's shape.

  S = @engr183.spec;   % shorthand: name, fn, args, expected, points [, tol]
  U = 'u04_apa04_parachute_sizing_check';

  specs = { ...
    S('Required files: both function files, the main script, and the public check exist', ...
      U, {'required_files'}, true, 1), ...

    S('parachute_speed: model calculations are correct and shape is preserved', ...
      U, {'parachute_speed_correctness'}, true, 2), ...

    S('parachute_speed: invalid inputs raise an error', ...
      U, {'parachute_speed_validation'}, true, 2), ...

    S('size_parachute: published and boundary search cases are correct', ...
      U, {'size_parachute_search_behavior'}, true, 4), ...

    S('size_parachute: general (nonpublished) cases are correct', ...
      U, {'size_parachute_general_cases'}, true, 2), ...

    S('size_parachute: invalid inputs raise an error', ...
      U, {'size_parachute_validation'}, true, 3), ...

    S('The supplied public-check file passes for a completed implementation', ...
      U, {'public_check_passes_when_solved'}, true, 1), ...
  };
end
