function specs = u04_gp04_thermal_monitor_tests()
%U04_GP04_THERMAL_MONITOR_TESTS  Rubric criteria for Unit 4's GP-04:
%   Processor Thermal Safety Monitor.
%
%   Run Tests calls classify_temperature and analyze_thermal_log directly
%   (per the assignment's own design -- it does not execute or parse the
%   main script's printed output). The actual checking logic lives in
%   u04_gp04_thermal_monitor_check.m, which runs each case in a disposable
%   try/catch and reports back one of the criteria below. Mirrors
%   unit02_check.m / u03_gp03_thermistor_check.m's shape.

  S = @engr183.spec;   % shorthand: name, fn, args, expected, points [, tol]
  U = 'u04_gp04_thermal_monitor_check';

  specs = { ...
    S('Required files: both function files and the main script exist', ...
      U, {'required_files'}, true, 1), ...

    S('classify_temperature: boundary classification is correct', ...
      U, {'classification_and_boundaries'}, true, 2), ...

    S('classify_temperature: invalid inputs raise an error', ...
      U, {'classification_validation'}, true, 2), ...

    S('analyze_thermal_log: the supplied seven-sample log is correct', ...
      U, {'complete_log_behavior'}, true, 2), ...

    S('analyze_thermal_log: shape is preserved and sentinels are correct', ...
      U, {'shape_and_sentinel_behavior'}, true, 2), ...

    S('analyze_thermal_log: invalid inputs raise an error', ...
      U, {'log_validation'}, true, 2), ...
  };
end
