function specs = u05_apa05_lake_perris_tests()
%U05_APA05_LAKE_PERRIS_TESTS  Rubric criteria for Unit 5's APA-05: Lake
%   Perris Reservoir Data Audit.
%
%   This assignment reads a frozen California Data Exchange Center (CDEC)
%   daily-storage CSV for Lake Perris into a validated structure
%   (read_reservoir_data.m), summarizes only the rows it marks valid
%   (summarize_reservoir.m) -- with every result index referring to a row
%   of the original structure -- and writes a labeled audit report
%   (write_reservoir_report.m), driven by a main script.
%
%   16 of this Canvas assignment's 20 points are automated code checks,
%   below. The remaining 4 points are manually graded in Canvas: the four
%   written reflection responses and overall label/unit/formatting
%   quality. A passing public check is not the same thing as passing the
%   correctness and main-script checks -- both are graded separately.
%
%   The actual checking logic lives in u05_apa05_lake_perris_check.m,
%   which resolves the student's files, runs them in isolated workspaces,
%   and reports back one of the criteria below. Mirrors
%   u03_apa03_processor_cooling_check.m's shape.

  S = @engr183.spec;   % shorthand: name, fn, args, expected, points [, tol]
  U = 'u05_apa05_lake_perris_check';

  specs = { ...
    S('Required files: the three functions, the main script, and the public check exist', ...
      U, {'required_files'}, true, 1), ...

    S('read_reservoir_data: parses the CSV and builds correct storage, date_code, and valid_mask', ...
      U, {'read_reservoir_data_correctness'}, true, 3), ...

    S('read_reservoir_data: invalid inputs raise an error', ...
      U, {'read_reservoir_data_validation'}, true, 2), ...

    S('summarize_reservoir: every value is correct and indices refer to original rows', ...
      U, {'summarize_reservoir_correctness'}, true, 3), ...

    S('summarize_reservoir: invalid inputs raise an error', ...
      U, {'summarize_reservoir_validation'}, true, 2), ...

    S('write_reservoir_report: writes a labeled report with dated results and the interpretation boundary', ...
      U, {'write_reservoir_report_output'}, true, 2), ...

    S('Function help documentation is complete for all three functions', ...
      U, {'function_help_documentation'}, true, 1), ...

    S('The supplied public check passes for a completed implementation', ...
      U, {'public_check_passes'}, true, 1), ...

    S('Main script: runs the full pipeline and confirms the output file and record counts', ...
      U, {'main_script_pipeline'}, true, 1), ...
  };
end
