function specs = u05_gp05_fault_creep_tests()
%U05_GP05_FAULT_CREEP_TESTS  Rubric criteria for Unit 5's GP-05: From
%   Sensor File to Engineering Summary.
%
%   This guided practice introduces reading a real delimited data file
%   into a validated structure (read_creep_data.m), then using that
%   structure in a main script to compute a record count, the slip
%   extremes and where they occur, and the largest day-to-day change --
%   distinguished from the net change -- before printing a summary and
%   writing a labeled report file.
%
%   9 of this Canvas assignment's 10 points are automated code checks,
%   below. The remaining 1 point is manually graded in Canvas: the three
%   written reflection comments -- an automated 9/9 here is not the same
%   thing as your full Canvas grade.
%
%   The actual checking logic lives in u05_gp05_fault_creep_check.m, which
%   resolves the student's files, runs them in isolated workspaces, and
%   reports back one of the criteria below. Mirrors
%   u04_gp04_thermal_monitor_check.m's shape.

  S = @engr183.spec;   % shorthand: name, fn, args, expected, points [, tol]
  U = 'u05_gp05_fault_creep_check';

  specs = { ...
    S('Required files: read_creep_data.m and the main script exist', ...
      U, {'required_files'}, true, 1), ...

    S('read_creep_data: structure fields, shapes, and values are correct', ...
      U, {'read_creep_data_correctness'}, true, 2), ...

    S('read_creep_data: invalid inputs raise an error', ...
      U, {'read_creep_data_validation'}, true, 2), ...

    S('read_creep_data: help documentation is complete', ...
      U, {'read_creep_data_help'}, true, 1), ...

    S('The supplied public check passes for a completed implementation', ...
      U, {'public_check_passes'}, true, 1), ...

    S('Main script: record count, slip extremes, and net vs. largest change are correct', ...
      U, {'main_script_summary'}, true, 2), ...

    S('Main script: prints a summary and writes a labeled report file', ...
      U, {'main_script_report'}, true, 1), ...
  };
end
