function specs = u06_apa06_battery_discharge_tests()
% Ten practice feedback points, separate from the Canvas rubric.
  u06_apa06_battery_discharge_check('reset');
  keys = {'personalization', 'execution', 'data', 'power', 'output', ...
          'arrangement', 'top', 'bottom', 'presentation', 'limits'};
  names = {'Personalization: completed Name and Date', 'Execution: script completes', ...
    'Given data: all samples and cutoff', 'Power calculations: both complete arrays', ...
    'Final-power output: Battery A and Battery B', 'Figure arrangement: two vertical panels', ...
    'Voltage panel: A, B and cutoff', 'Power panel: both calculated records', ...
    'Presentation: labels, grid, legends, styles', 'Axis limits: include all supplied values'};
  specs = cell(1, numel(keys));
  for k = 1:numel(keys)
    specs{k} = engr183.spec(names{k}, 'u06_apa06_battery_discharge_check', {keys{k}}, true, 1);
  end
end
