function specs = u07_apa07_force_recovery_tests()
% Twelve one-point practice checks; not a final Canvas grade.
  u07_apa07_force_recovery_check('reset');
  keys = {'personalization', ...
    'execution', ...
    'inputs', ...
    'matrix', ...
    'helper', ...
    'baseline', ...
    'residual', ...
    'known', ...
    'application', ...
    'change', ...
    'plot', ...
    'output'};
  names = {'Personalization: completed Name and Date', ...
    'Execution: main script completes', ...
    'Inputs: values and scalar/column dimensions', ...
    'Matrix: supplied coefficients and right side', ...
    'Helper: general solves and input rejection', ...
    'Baseline: solution, rank and conditioning', ...
    'Residual: matching equations and maximum', ...
    'Known answer: independent data and error', ...
    'Application: whole-vector percent changes', ...
    'Changed system: solution and sensitivity', ...
    'Plot: data, labels, legend, styles and range', ...
    'Output: labeled numbers and units'};
  specs = cell(1,numel(keys));
  for k = 1:numel(keys)
    specs{k} = engr183.spec(names{k}, 'u07_apa07_force_recovery_check', {keys{k}}, true, 1);
  end
end
