function specs = u08_project_solar_station_tests()
% Formative programming feedback only; the PDF is reviewed separately.
  u08_project_solar_station_check('reset');
  keys = {'cleaning','power','summaries','helper_costs','helper_decisions', ...
          'branching','integration','recommendation','dynamic','power_plot','percent_plot','output'};
  names = {'Data: import and one shared cleaning mask (TODO 1-2)', ...
    'Power: element-wise values and sensor columns (TODO 2-3)', ...
    'Summaries: all retained observations, counts and units (TODO 3)', ...
    'Helper costs: quantities times unit prices and calculated sum (TODO 4a)', ...
    'Helper decisions: four outcomes and inclusive boundaries (TODO 4b)', ...
    'Required technique: executable decision branching (TODO 4b)', ...
    'Integration: helper arguments and all returned values (TODO 4)', ...
    'Recommendation: cheapest qualifying system (TODO 5)', ...
    'Changed inputs: price change and no qualifying system (TODO 4-5)', ...
    'Power figure: selected day, three systems and 100 W (TODO 7)', ...
    'Percentage figure: all days, bars and 80 percent (TODO 7)', ...
    'Output: counts, labeled comparison and recommendation (TODO 6)'};
  specs = cell(1,numel(keys));
  for k = 1:numel(keys)
    specs{k} = engr183.spec(names{k}, 'u08_project_solar_station_check', {keys{k}}, true, 1);
  end
end
