function specs = unit01_tests()
%UNIT01_TESTS  Rubric criteria for Unit 1: OR-01 GNU Octave Setup and First
%   Script.
%
%   The purpose of this unit is to confirm that Octave is installed and
%   working on your machine, and to introduce the way every later unit
%   will be checked. All 8 criteria below are automated code checks; the
%   Canvas assignment is worth 10 points total, and the remaining 2 are
%   manually graded for a readable screenshot and a complete submission --
%   an 8/8 here is not the same thing as your Canvas grade.
%
%   The actual checking logic lives in unit01_check.m, which resolves your
%   script, runs it in an isolated workspace, and reports back one of the
%   criteria below.

  S = @engr183.spec;   % shorthand: name, fn, args, expected, points [, tol]
  U = 'unit01_check';

  specs = { ...
    S('Personalization: Name comment replaced', ...
      U, {'name_placeholder'}, true, 1), ...

    S('Personalization: Date comment replaced', ...
      U, {'date_placeholder'}, true, 1), ...

    S('Personalization: student_name holds your name', ...
      U, {'student_name_value'}, true, 1), ...

    S('Stored values and calculation are correct', ...
      U, {'stored_values'}, true, 3), ...

    S('Required labeled output prints, in order', ...
      U, {'output_lines'}, true, 2), ...
  };
end
