function specs = unit02_tests()
%UNIT02_TESTS  Rubric criteria for Unit 2: APA-02 Solar-Panel I-V Data
%   Analysis.
%
%   6 criteria below are automated code checks, worth 8 points; the
%   Canvas assignment is worth 10 points total, and the remaining 2 are
%   manually graded for labels, units, comments, and a complete
%   submission -- an 8/8 here is not the same thing as your Canvas grade.
%
%   The actual checking logic lives in unit02_check.m, which resolves
%   your script, runs it in an isolated workspace, and reports back one
%   of the criteria below.

  S = @engr183.spec;   % shorthand: name, fn, args, expected, points [, tol]
  U = 'unit02_check';

  specs = { ...
    S('Personalization: Name comment replaced', ...
      U, {'name_placeholder'}, true, 1), ...

    S('Personalization: Date comment replaced', ...
      U, {'date_placeholder'}, true, 1), ...

    S('measurement_count and power_W are correct', ...
      U, {'power_calculation'}, true, 1), ...

    S('Maximum power point is identified correctly', ...
      U, {'mpp_identification'}, true, 2), ...

    S('Fill factor and normalized vectors are correct', ...
      U, {'fill_factor_and_norm'}, true, 2), ...

    S('High-power mask and results matrix are correct', ...
      U, {'mask_and_results'}, true, 1), ...
  };
end
