function specs = unit00_tests()
%UNIT00_TESTS  Rubric criteria for Unit 00: Getting Started.
%
%   The purpose of this unit is to confirm that Octave is installed and
%   working on your machine, and to introduce the way every later unit
%   will be checked.  The math is deliberately trivial.

  S = @engr183.spec;   % shorthand: name, fn, args, expected, points [, tol]

  specs = { ...
    S('addTwo returns the sum of two positive numbers', ...
      'addTwo', {2, 3}, 5, 5), ...

    S('addTwo works with negative numbers', ...
      'addTwo', {-4, 1}, -3, 5), ...

    S('addTwo works with decimals', ...
      'addTwo', {0.1, 0.2}, 0.3, 5, 1e-9), ...

    S('circleArea computes the area of a unit circle', ...
      'circleArea', {1}, pi, 5, 1e-9), ...

    S('circleArea scales correctly with radius', ...
      'circleArea', {3}, 9*pi, 5, 1e-9), ...

    S('greet builds the expected greeting string', ...
      'greet', {'Ada'}, 'Hello, Ada!', 5), ...
  };
end
