function [line_cost_USD, total_cost_USD, qualifies, status_code] = ...
    evaluate_system(component_quantity, unit_price_USD, met_pct, ...
                    budget_USD, minimum_met_pct)
% EVALUATE_SYSTEM Calculate component costs and classify one system.
% Quantities and unit prices are matching row vectors; prices are $/item.
% Return one of: 'qualifies', 'fails_performance', 'over_budget', 'fails_both'.

    % Supplied input checks: keep these lines.
    assert(isnumeric(component_quantity) && isreal(component_quantity) && ...
        isrow(component_quantity) && ~isempty(component_quantity), ...
        'Quantities must be a nonempty real numeric row vector.');
    assert(isnumeric(unit_price_USD) && isreal(unit_price_USD) && ...
        isequal(size(unit_price_USD), size(component_quantity)), ...
        'Unit prices must match the quantity vector.');
    assert(all(isfinite(component_quantity)) && ...
        all(component_quantity >= 0) && all(isfinite(unit_price_USD)) && ...
        all(unit_price_USD >= 0), 'Quantities and prices must be finite and nonnegative.');
    assert(isnumeric(met_pct) && isreal(met_pct) && isscalar(met_pct) && ...
        isfinite(met_pct) && met_pct >= 0 && met_pct <= 100, ...
        'met_pct must be a finite scalar percentage from 0 to 100.');
    assert(isnumeric(budget_USD) && isreal(budget_USD) && isscalar(budget_USD) && ...
        isfinite(budget_USD) && budget_USD >= 0, ...
        'Budget must be a finite nonnegative scalar.');
    assert(isnumeric(minimum_met_pct) && isreal(minimum_met_pct) && ...
        isscalar(minimum_met_pct) && isfinite(minimum_met_pct) && ...
        minimum_met_pct >= 0 && minimum_met_pct <= 100, ...
        'Required percentage must be a finite scalar from 0 to 100.');

    % TODO 4a: Calculate line_cost_USD = quantity times UNIT price,
    % using matching elements. Then sum all line costs into total_cost_USD.

    % TODO 4b: Use if / elseif / else with the CALCULATED total cost and
    % supplied percentage/thresholds to classify the system. Return scalar
    % logical qualifies and the appropriate status_code. Support all four
    % outcomes, including 'fails_both'. Equality meets both requirements.
end
